/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Jni */

#ifndef _Included_Jni
#define _Included_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Jni
 * Method:    getMossaBot
 * Signature: (I[[III)[I
 */
JNIEXPORT jintArray JNICALL Java_Jni_getMossaBot
  (JNIEnv *, jobject, jint, jobjectArray, jint, jint);

/*
 * Class:     Jni
 * Method:    stampami
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Jni_stampami
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
