/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Jni */

#ifndef _Included_Jni
#define _Included_Jni
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     Jni
	 * Method:    getMossaBot
	 * Signature: (I[[III)[I
	 */
	JNIEXPORT jintArray JNICALL Java_Jni_getMossaBot
	(JNIEnv*, jobject, jint, jobjectArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif#pragma once
